import type { Category, WorkItem } from "./types";
import {
  Alpi,
  AlpiTruck,
  AmiShop,
  Biznesi,
  Doros1,
  FastyolMaica,
  FletoreFluent,
  Heinen,
  Kos,
  Libri,
  Marmo,
  Marmobox,
  Neki,
  Pekon,
  RenovaTruck,
  Simpo,
  ThreeMenu,
  ThreeParkjuice,
  ThreeParkKoktell,
  ThreePleksMenu,
} from "@/assets/images/index";

import {
  Remall,
  Renova,
  Doros,
  Atomic,
  Ultra,
  Andona,
  BioVita,
  CarGlans,
  FaselTrans,
  Fluent,
  Fokus,
  Foster,
  FwmPartner,
  GeoMaster,
  HajriKom,
  Hallall,
  HeinenGroup,
  Iliret,
  IsoGips,
  Kiel,
  Lartana,
  Liney,
  MarmoFix,
  Mercure,
  // Metal4,
  Phoenix,
  Possible,
  PROAfroVal,
  RoletLux,
  Shpendi,
  Telem,
  // ThreePark,
  ValkLogistik,
  Verona,
} from "@/assets/client-logos/index";

export const TRUSTED_COMPANIES = [
  { name: "Atomic", Logo: Atomic },
  { name: "BioVita", Logo: BioVita },
  { name: "Renova", Logo: Renova },
  { name: "Doros", Logo: Doros },
  { name: "Ultra", Logo: Ultra },
  { name: "Remall", Logo: Remall },
  { name: "MarmoFix", Logo: MarmoFix },
  { name: "Mercure", Logo: Mercure },
  { name: "FaselTrans", Logo: FaselTrans },
  { name: "Fluent", Logo: Fluent },
  { name: "Fokus", Logo: Fokus },
  { name: "Foster", Logo: Foster },
  { name: "Andona", Logo: Andona },
  { name: "FwmPartner", Logo: FwmPartner },
  { name: "CarGlans", Logo: CarGlans },
  { name: "RoletLux", Logo: RoletLux },
  { name: "GeoMaster", Logo: GeoMaster },
  { name: "HajriKom", Logo: HajriKom },
  { name: "HeinenGroup", Logo: HeinenGroup },
  { name: "Hallall", Logo: Hallall },
  { name: "Iliret", Logo: Iliret },
  { name: "IsoGips", Logo: IsoGips },
  { name: "Kiel", Logo: Kiel },
  { name: "Lartana", Logo: Lartana },
  { name: "Liney", Logo: Liney },
  // { name: "Metal4", Logo: Metal4 },
  { name: "Phoenix", Logo: Phoenix },
  { name: "Possible", Logo: Possible },
  { name: "PROAfroVal", Logo: PROAfroVal },
  { name: "Shpendi", Logo: Shpendi },
  { name: "Telem", Logo: Telem },
  // { name: "ThreePark", Logo: ThreePark },
  { name: "ValkLogistik", Logo: ValkLogistik },
  { name: "Verona", Logo: Verona },
];

export const CATEGORIES: Category[] = [
  "KREJT",
  "LOGO DIZAJN",
  "PRINTIM DIGJITAL",
  "PRODUKTE PROMOCIONALE",
  "DIZAJN I PRODUKTEVE",
  "PRODUKTE TEKSTILI",
];

export const WORK_ITEMS: WorkItem[] = [
  {
    title: "AUTOBUS ME FOLI",
    name: "Alpi",
    category: "PRINTIM DIGJITAL",
    image: Alpi,
  },
  {
    title: "KAMJON ME FOLI",
    name: "Alpi ",
    category: "PRINTIM DIGJITAL",
    image: AlpiTruck,
  },
  {
    title: "LOGO",
    name: "Ami Shop",
    category: "LOGO DIZAJN",
    image: AmiShop,
  },
  {
    title: "LOGO",
    name: "Biznesi",
    category: "LOGO DIZAJN",
    image: Biznesi,
  },
  {
    title: "PAKETIM",
    name: "Doros",
    category: "DIZAJN I PRODUKTEVE",
    image: Doros1,
  },
  {
    title: "MAICA",
    name: "Fastyol",
    category: "PRODUKTE TEKSTILI",
    image: FastyolMaica,
  },
  {
    title: "FLETORE",
    name: "Fluent",
    category: "PRODUKTE PROMOCIONALE",
    image: FletoreFluent,
  },

  {
    title: "VETURA ME FOLI",
    name: "Heinen",
    category: "PRINTIM DIGJITAL",
    image: Heinen,
  },
  {
    title: "KOS",
    name: "BIO VITA",
    category: "DIZAJN I PRODUKTEVE",
    image: Kos,
  },
  {
    title: "LIBËR",
    name: "BEQIR MEMETI",
    category: "DIZAJN I PRODUKTEVE",
    image: Libri,
  },
  {
    title: "KATALOG",
    name: "Marmofix",
    category: "PRODUKTE PROMOCIONALE",
    image: Marmo,
  },
  {
    title: "KOVA",
    name: "Marmofix",
    category: "DIZAJN I PRODUKTEVE",
    image: Marmobox,
  },
  {
    title: "KASETA",
    name: "Neki Emra",
    category: "DIZAJN I PRODUKTEVE",
    image: Neki,
  },
  {
    title: "PAKETIM BUKE",
    name: "Pekon",
    category: "DIZAJN I PRODUKTEVE",
    image: Pekon,
  },
  {
    title: "KAMJON ME FOLI",
    name: "Renova",
    category: "PRINTIM DIGJITAL",
    image: RenovaTruck,
  },
  {
    title: "BUS STOP ME FOLI",
    name: "Alpi",
    category: "PRINTIM DIGJITAL",
    image: Simpo,
  },
  {
    title: "MENU",
    name: "Three Park",
    category: "PRODUKTE PROMOCIONALE",
    image: ThreeMenu,
  },
  {
    title: "MENU",
    name: "Three Park",
    category: "PRODUKTE PROMOCIONALE",
    image: ThreeParkKoktell,
  },
  {
    title: "MENU",
    name: "Three Park",
    category: "PRODUKTE PROMOCIONALE",
    image: ThreeParkjuice,
  },
  {
    title: "PLEKS MENU",
    name: "Three Park",
    category: "PRODUKTE PROMOCIONALE",
    image: ThreePleksMenu,
  },
];

export const NAV_ITEMS = [
  {
    name: "ballina",
  },
  {
    name: "rreth nesh",
  },
  {
    name: "klientela",
  },
  {
    name: "xhi ofrojm ne?",
  },
  {
    name: "na kontakto",
  },
];

//navbar: ballina, rreth nesh, klientet, sherbimet, kontakt
